### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by GDD-josh** [Lutes/lisnd#13]
On reviews

**Comment by Lutes** [comment]
@GDD-josh Can you build the back-end for commenting. I need this for building the review page

**Comment by GDD-josh** [comment]
Ye I build a basic front end on the album page, can you make this into a directive?

**Comment by Lutes** [comment]
@GDD-josh What do you mean? Like make a comment be a directive?

**Comment by GDD-josh** [comment]
Yeah because we to add comments everywhere

**Comment by Lutes** [comment]
Made the Comment Directive. But think that we should push back the feature from the beta until we refactor.

**Comment by GDD-josh** [comment]
why?

**Comment by GDD-josh** [comment]
I have everything set up for deleting and editing comments? Should we leave this out for the beta?
