### ISSUE TITLE
Set-up bussiness gmail for our domain

### ISSUE THREAD

**Issue by Lutes** [Lutes/lisnd#21]
Create email addresses with the @listnd domain.

**Comment by jared-randall** [comment]
It's $5 per user. Does everyone agree to that? @Lutes @GDD-josh @PresidentBaby

**Comment by GDD-josh** [comment]
yea

**Comment by jared-randall** [comment]
At what point do we set-up a business bank account?

**Comment by Lutes** [comment]
@jared-randall  Can you create a spreadsheet that tracks expenses? We can just add them in there for now.
