### ISSUE TITLE
Add tracks from albums with multiple cds

### ISSUE THREAD

**Issue by GDD-josh** [Lutes/lisnd#33]

**Comment by GDD-josh** [comment]
@PresidentBaby What was the album that had this problem?

**Comment by PresidentBaby** [comment]
http://listnd.com:8080/#/album/09425c87-54fa-4438-b13e-3e35b70a7953

The album is Have One On Me by Joanna Newsom -- it actually has 18 tracks
as part of a triple album, but only the first part shows up
